### ISSUE TITLE
Solution to problem 1

### ISSUE THREAD

**Issue by Nilesh2000** [SVCE-HacktoberFest2019/AlgorithmsDaily#1]

**Comment by Elenaires** [comment]
Can I be assigned to work on this please? :)

**Comment by Nilesh2000** [comment]
Well, I want as many people as possible to contribute to this repository. So, it really wouldn't be possible to assign you this issue.

**Comment by JHero23** [comment]
Is this issue still eligible for hacktoberfest? I noticed that the FAQs in hacktoberfest say that it must be open, that or I may be reading it wrong. See section "How do I get started?" [here](https://hacktoberfest.digitalocean.com/faq)
